# -*- coding: utf-8 -*-
"""Text2SqlLora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EScWvOUE46B-4LybhPENfa5msTCyErnK

Install Dependencies
"""

!pip install -q transformers sentence-transformers datasets faiss-cpu torch accelerate
!pip install -q bitsandbytes peft safetensors sqlparse tabulate sqlite-utils

"""Unzip Spider Dataset"""

import zipfile, os, json
from pathlib import Pathpr

ZIP_PATH = "/content/spider_data.zip"
EXTRACT_DIR = "/content/spider_data"
SPIDER_BASE = os.path.join(EXTRACT_DIR, "spider_data")

if os.path.exists(ZIP_PATH) and not os.path.exists(EXTRACT_DIR):
  with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(EXTRACT_DIR)
  print("Extracted.")
else:
  print("Zip not found or already extracted.")

assert os.path.exists(SPIDER_BASE)

"""Load Spider Schema"""

with open(os.path.join(SPIDER_BASE, 'tables.json'),'r') as f:
  tables_json = json.load(f)

with open(os.path.join(SPIDER_BASE, 'train_spider.json'),'r') as f:
  train_json = json.load(f)

DEV_PATH = os.path.join(SPIDER_BASE, 'dev.json')
with open(DEV_PATH,'r') as f:
  dev_json = json.load(f)

print("Train:", len(train_json), "Dev:", len(dev_json))

# Build {db → {table → [cols]}}
db_schemas = {}
for entry in tables_json:
  dbid = entry["db_id"]
  table_names = entry["table_names_original"]
  cols_by_table = {t: [] for t in table_names}
  for ti, col in entry["column_names_original"]:
    if ti != -1:
      cols_by_table[table_names[ti]].append(col)
  db_schemas[dbid] = cols_by_table

"""Schema Embeddings"""

from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer("all-MiniLM-L6-v2")

db_col_embeddings = {}

for dbid, tmap in db_schemas.items():
    col_names = []
    col_to_table = []
    for t, cols in tmap.items():
        for c in cols:
            col_names.append(f"{t}.{c}")
            col_to_table.append((t, c))
    if col_names:
        db_col_embeddings[dbid] = {
            "col_names": col_names,
            "embeddings": embedder.encode(col_names, convert_to_tensor=True),
            "col_to_table": col_to_table
        }

"""Schema Linking + Prompt Builder"""

import re

def schema_link_simple(dbid, query, top_k=5):
    schema = db_schemas[dbid]
    q = query.lower()
    scored = []
    for t, cols in schema.items():
        s = 0
        if t.lower() in q: s += 2
        for c in cols:
            if c.lower() in q: s += 2
        scored.append((s,t))
    scored.sort(reverse=True)
    return [t for s,t in scored if s>0][:top_k]

def schema_link_embed(dbid, query, top_k=10):
    data = db_col_embeddings.get(dbid)
    if data is None: return []
    q_emb = embedder.encode(query, convert_to_tensor=True)
    hits = util.semantic_search(q_emb, data["embeddings"], top_k=top_k)[0]
    counter = {}
    for h in hits:
        t, c = data["col_to_table"][h["corpus_id"]]
        counter[t] = counter.get(t, 0) + 1
    return [t for t, _ in sorted(counter.items(), key=lambda x:-x[1])]

def schema_to_string(schema):
    return "\n".join(f"{t}({', '.join(cols)})" for t, cols in schema.items())

def build_prompt(dbid, query):
    top = schema_link_simple(dbid, query)
    if len(top) < 2:
        top = schema_link_embed(dbid, query)[:5]

    relevant = {t: db_schemas[dbid][t] for t in top}

    schema_text = "\n".join(
        f"{t}({', '.join(cols)})"
        for t, cols in relevant.items()
    )

    return (
        "<s>You are a SQL generator.\n"
        "Convert the natural language question into **SQLite SQL**.\n"
        "Rules:\n"
        "1. Output ONLY SQL.\n"
        "2. Use ONLY the schema below.\n"
        "3. Always use JOIN .. ON with correct keys.\n"
        "4. End output with a semicolon.\n\n"
        f"Schema:\n{schema_text}\n\n"
        f"Question: {query}\nSQL:\n"
    )

"""Dataset Class"""

from huggingface_hub import login
login()

from torch.utils.data import Dataset
from transformers import AutoTokenizer

MODEL_NAME = "meta-llama/Llama-3.2-3B"
MAX_LENGTH = 1024

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': tokenizer.eos_token})

class SQLDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=1024):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        prompt = self.data[idx]["prompt"]
        sql = self.data[idx]["sql"].strip().rstrip(";") + ";"

        full_text = f"{prompt}{sql}</s>"   # important

        enc = self.tokenizer(
            full_text,
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt",
        )

        input_ids = enc["input_ids"].squeeze(0)
        labels = input_ids.clone()

        # MASK EVERYTHING BEFORE SQL
        prompt_len = len(self.tokenizer(prompt)["input_ids"])

        labels[:prompt_len] = -100  # IGNORE prompt tokens

        return {
            "input_ids": input_ids,
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": labels,
        }

# Build training examples
train_data = []
for item in train_json:
    train_data.append({
        "prompt": build_prompt(item["db_id"], item["question"]),
        "sql": item["query"],
    })

train_dataset = SQLDataset(train_data, tokenizer)

"""Load Model + Apply LoRA"""

from transformers import AutoModelForCausalLM
from peft import LoraConfig, get_peft_model
import torch

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto"
)

model.config.use_cache = False  # IMPORTANT

lora_cfg = LoraConfig(
    r=32,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_cfg)
model.print_trainable_parameters()

"""Trainer"""

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="/content/sql_lora_out",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    warmup_steps=50,

    fp16=True,
    logging_steps=50,
    save_strategy="epoch",
    remove_unused_columns=False,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=tokenizer
)

"""Train"""

trainer.train()
trainer.save_model("/content/sql_lora_out/peft")
tokenizer.save_pretrained("/content/sql_lora_out/tokenizer")

!zip -r sql_lora_finetune_ready.zip /content/sql_lora_out

from google.colab import files
files.download("sql_lora_finetune_ready.zip")