# -*- coding: utf-8 -*-
"""Text2SqlEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QW60WrPEnp6wkfSphk8FOf8IxBFDk7z

Unzip the fine tuned model
"""

!sudo apt-get update -y
!sudo apt-get install python3.10 python3.10-distutils -y

!curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

import zipfile, os

zip_path = "/content/sql_lora_finetune_ready (1).zip"
extract_path = "/content/sql_lora_out"

# Create extraction directory if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extracted:", extract_path)

# List contents to verify
!ls -R {extract_path}

# ---------------------------
# Fixed full script (copy-paste)
# ---------------------------

!pip install -q transformers sentence-transformers datasets faiss-cpu torch accelerate peft safetensors sqlparse tabulate sqlite-utils

import os, zipfile, json, sqlite3, sqlparse, torch
from pathlib import Path
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from sentence_transformers import SentenceTransformer, util

# ---------------------------
# Paths
# ---------------------------
SPIDER_DATA_ROOT = "/content/spider_data"
SPIDER_BASE = os.path.join(SPIDER_DATA_ROOT, "spider_data")  # contains dev.json, tables.json
DB_ROOT = os.path.join(SPIDER_DATA_ROOT, "spider_data", "database")  # <- folder that contains per-db folders

PEFT_DIR = "/content/sql_lora_out/content/sql_lora_out/peft"
BASE_MODEL = "meta-llama/Llama-3.2-3B"
TOKENIZER_DIR = "/content/sql_lora_out/content/sql_lora_out/tokenizer"

# ---------------------------
# Load spider jsons
# ---------------------------
print("Spider data ready (assuming extracted by previous cells).")
with open(os.path.join(SPIDER_BASE, "dev.json")) as f:
    dev_json = json.load(f)
with open(os.path.join(SPIDER_BASE, "tables.json")) as f:
    tables_json = json.load(f)
print("Tables:", len(tables_json), "Dev examples:", len(dev_json))

# ---------------------------
# Build schema dict
# ---------------------------
db_schemas = {}
for entry in tables_json:
    dbid = entry["db_id"]
    table_names = entry["table_names_original"]
    cols_by_table = {t: [] for t in table_names}
    for ti, col in entry["column_names_original"]:
        if ti != -1:
            cols_by_table[table_names[ti]].append(col)
    db_schemas[dbid] = cols_by_table

# ---------------------------
# Load model + LoRA adapter
# ---------------------------
print("Loading base model (may take a while)...")
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto",
)
model = PeftModel.from_pretrained(model, PEFT_DIR)
print("      + PEFT loaded.")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_DIR, fix_mistral_regex=True)
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': tokenizer.eos_token})

# Determine device to send inputs to (works for device_map="auto" models too)
try:
    model_device = model.device
except Exception:
    # fallback - get device of first parameter
    model_device = next(model.parameters()).device

print("Model device (for inputs):", model_device)

# ---------------------------
# Column embeddings for schema linking
# ---------------------------
embedder = SentenceTransformer("all-MiniLM-L6-v2")
db_col_embeddings = {}
for dbid, tmap in db_schemas.items():
    col_names, col_to_table = [], []
    for t, cols in tmap.items():
        for c in cols:
            col_names.append(f"{t}.{c}")
            col_to_table.append((t, c))
    if col_names:
        db_col_embeddings[dbid] = {
            "col_names": col_names,
            "embeddings": embedder.encode(col_names, convert_to_tensor=True),
            "col_to_table": col_to_table
        }

# ---------------------------
# Schema linking functions
# ---------------------------
def schema_link_simple(dbid, query, top_k=5):
    schema = db_schemas[dbid]
    q = query.lower()
    scored = []
    for t, cols in schema.items():
        s = 0
        if t.lower() in q: s += 2
        for c in cols:
            if c.lower() in q: s += 2
        scored.append((s,t))
    scored.sort(reverse=True)
    return [t for s,t in scored if s>0][:top_k]

def schema_link_embed(dbid, query, top_k=10):
    data = db_col_embeddings.get(dbid)
    if data is None: return []
    q_emb = embedder.encode(query, convert_to_tensor=True)
    hits = util.semantic_search(q_emb, data["embeddings"], top_k=top_k)[0]
    counter = {}
    for h in hits:
        t, c = data["col_to_table"][h["corpus_id"]]
        counter[t] = counter.get(t, 0) + 1
    return [t for t, _ in sorted(counter.items(), key=lambda x:-x[1])]

def build_prompt(dbid, query):
    top = schema_link_simple(dbid, query)
    if len(top) < 2:
        top = schema_link_embed(dbid, query)[:5]
    relevant = {t: db_schemas[dbid][t] for t in top}
    schema_text = "\n".join(f"{t}({', '.join(cols)})" for t, cols in relevant.items())
    return (
        "<s>You are a SQL generator.\n"
        "Convert the natural language question into **SQLite SQL**.\n"
        "Rules:\n"
        "1. Output ONLY SQL.\n"
        "2. Use ONLY the schema below.\n"
        "3. Always use JOIN .. ON with correct keys.\n"
        "4. End output with a semicolon.\n\n"
        f"Schema:\n{schema_text}\n\n"
        f"Question: {query}\nSQL:\n"
    )

def clean_sql(output):
    if "SQL:" not in output:
        return None
    sql = output.split("SQL:", 1)[1]
    sql = sql.split("</s>")[0].strip()
    sql = sql.split(";")[0].strip() + ";"
    return sql if len(sql) >= 5 else None

# ---------------------------
# Generate SQL for one question (fixed DB path)
# ---------------------------
def egd_generate(dbid, question, k=5):
    prompt = build_prompt(dbid, question)
    inputs = tokenizer(prompt, return_tensors="pt")
    # move inputs to the same device the model expects
    inputs = {k: v.to(model_device) for k,v in inputs.items()}

    outputs = model.generate(
        **inputs,
        max_new_tokens=256,
        do_sample=False
    )

    # correct DB path: database/<dbid>/<dbid>.sqlite
    db_path = os.path.join(DB_ROOT, dbid, f"{dbid}.sqlite")
    if not os.path.exists(db_path):
        print("❌ Database not found at (egd_generate):", db_path)
    else:
        print("✅ Using DB (egd_generate):", db_path)

    for o in outputs:
        decoded = tokenizer.decode(o, skip_special_tokens=True)
        print("--- RAW MODEL OUTPUT ---")
        print(decoded)
        print("------------------------")
        sql = clean_sql(decoded)
        if not sql:
            print(f"Warning: clean_sql returned None for output (truncated): {decoded[:200]}...")
            continue
        try:
            con = sqlite3.connect(db_path)
            cur = con.cursor()
            print(f"Attempting to execute SQL: {sql}")
            cur.execute(sql)
            rows = cur.fetchall()
            con.close()
            return sql, rows
        except Exception as e:
            print(f"SQL execution failed for db {dbid} with query: {sql}")
            print("Error:", e)
            continue

    return None, None

# ---------------------------
# Evaluate (fixed db_path building)
# ---------------------------
def evaluate(limit=200):
    exact = exec_acc = total = 0
    for item in dev_json[:limit]:
        total += 1
        gold = item["query"].strip().rstrip(";") + ";"
        dbid = item["db_id"]   # use the dev item's dbid
        pred, _ = egd_generate(dbid, item["question"])
        if not pred:
            # still count this example in total (so metrics are conservative)
            continue
        # Normalize
        g = sqlparse.format(gold, keyword_case="lower")
        p = sqlparse.format(pred, keyword_case="lower")
        if g == p:
            exact += 1
        # Execution accuracy
        db_path = os.path.join(DB_ROOT, dbid, f"{dbid}.sqlite")
        if not os.path.exists(db_path):
            print("❌ Database not found (evaluate):", db_path)
            continue
        con = sqlite3.connect(db_path)
        cur = con.cursor()
        try:
            cur.execute(pred)
            p_rows = cur.fetchall()
            cur.execute(gold)
            g_rows = cur.fetchall()
            if p_rows == g_rows:
                exec_acc += 1
        except Exception as e:
            # print("Execution failed on either pred or gold:", e)
            pass
        finally:
            con.close()

    return {
        "exact_match": exact / total if total>0 else 0.0,
        "execution_accuracy": exec_acc / total if total>0 else 0.0
    }

# ---------------------------
# Run a small eval
# ---------------------------
scores = evaluate(limit=20)
print("Evaluation scores:", scores)

# ---------------------------
# Test generation examples
# ---------------------------
examples = [
    "How many singers do we have?",
    "What is the total number of singers?",
    "Show name, country, age for all singers ordered by age from the oldest to the youngest.",
]
for q in examples:
    sql, rows = egd_generate(dev_json[0]["db_id"], q)
    print("\nQuestion:", q)
    print("Generated SQL:", sql)
    print("Rows:", rows)

import os
print(os.path.exists("/content/spider_data/spider_data/database/singer/singer.sqlite"))