# -*- coding: utf-8 -*-
"""TrainSql2NoSqlFullData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fIUwnLpMaYzoDw4ambgyAzAm1WwEigGM
"""

from zipfile import ZipFile
import os

ZIP_PATH = "/content/sql_lora_finetune_ready.zip"
EXTRACT_PATH = "/content/sql_lora"

os.makedirs(EXTRACT_PATH, exist_ok=True)

with ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_PATH)

print("Extracted files:", os.listdir(EXTRACT_PATH))

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

BASE_MODEL = "meta-llama/Llama-3.2-3B"
EXISTING_LORA = "/content/sql_lora/content/sql_lora_out/peft"
TOKENIZER_PATH = "/content/sql_lora/content/sql_lora_out/tokenizer"

tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

# 🔥 Load EXACT same LoRA adapter
model = PeftModel.from_pretrained(base_model, EXISTING_LORA)
model.print_trainable_parameters()

model.config.use_cache = False

import json

sql_mongo_data = []

with open("/content/train_nosql (1).json", "r") as f:
    # Read the entire file content
    file_content = f.read()
    # Parse the entire content as a single JSON object (expected to be a list)
    sql_mongo_data = json.loads(file_content)

print("Loaded samples:", len(sql_mongo_data))
print("First sample keys:", sql_mongo_data[0].keys())

def build_sql_to_mongo_prompt(sql):
    return (
        "<s>Convert this SQL query to an equivalent MongoDB query.\n\n"
        "Rules:\n"
        "1. Output ONLY MongoDB query.\n"
        "2. Use aggregate() for JOIN or GROUP BY.\n"
        "3. No explanation.\n\n"
        f"SQL:\n{sql}\n\n"
        "MongoDB:\n"
    )

from torch.utils.data import Dataset

class SQLToMongoDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=1024):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sql = self.data[idx]["SQL"].strip()
        mongo = self.data[idx]["generated_nosql"].strip()

        prompt = build_sql_to_mongo_prompt(sql)
        full_text = f"{prompt}{mongo}</s>"

        enc = self.tokenizer(
            full_text,
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt"
        )

        input_ids = enc["input_ids"].squeeze(0)
        labels = input_ids.clone()

        prompt_len = len(self.tokenizer(prompt)["input_ids"])
        labels[:prompt_len] = -100  # 🔥 mask SQL

        return {
            "input_ids": input_ids,
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": labels,
        }



train_dataset = SQLToMongoDataset(sql_mongo_data, tokenizer)

from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(sql_mongo_data, test_size=0.2, random_state=42)

print(f"Training data size: {len(train_data)}")
print(f"Test data size: {len(test_data)}")

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/sql_lora_extended",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,
    warmup_steps=10,

    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    remove_unused_columns=False,
    report_to="none",
    per_device_eval_batch_size=1, # Add this to reduce batch size during evaluation/prediction
    eval_accumulation_steps=8 # Accumulate predictions to handle larger evaluation sets with small batch size
)

from peft.tuners.lora import LoraLayer

# 1. Freeze everything
for p in model.parameters():
    p.requires_grad = False

# 2. Unfreeze ONLY LoRA matrices (A and B)
for module in model.modules():
    if isinstance(module, LoraLayer):
        module.lora_A["default"].weight.requires_grad = True
        module.lora_B["default"].weight.requires_grad = True

model.print_trainable_parameters()

from transformers import Trainer

# Create the training dataset from the split data
train_dataset_for_trainer = SQLToMongoDataset(train_data, tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_for_trainer, # Use the SQLToMongoDataset instance
    tokenizer=tokenizer # Pass the tokenizer correctly
)

trainer.train()

trainer.save_model("/content/sql_lora_out/peft")

trainer.save_model("/content/sql_lora_out_sql_mongo/peft")
tokenizer.save_pretrained("/content/sql_lora_out_sql_mongo/tokenizer")

import shutil
import os

LORA_DIR = "/content/sql_lora_out"
ZIP_PATH = "/content/lora_sql_to_mongo2"

assert os.path.exists(LORA_DIR), "LoRA directory not found!"

shutil.make_archive(
    ZIP_PATH,
    "zip",
    LORA_DIR
)

print("ZIP created at:", ZIP_PATH + ".zip")



# Create the test dataset from the split data
test_dataset = SQLToMongoDataset(test_data, tokenizer)

# Re-initialize the Trainer to pick up updated training_args (especially per_device_eval_batch_size)
# The model weights are already loaded from the previous training run.
from transformers import Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=None, # No need for train_dataset for prediction only
    tokenizer=tokenizer
)

# Clear CUDA cache before prediction to free up memory
import torch
torch.cuda.empty_cache()

# --- MANUAL PREDICTION LOOP TO AVOID OOM ---

from torch.utils.data import DataLoader

# Use a DataLoader for batching during manual inference
eval_batch_size = training_args.per_device_eval_batch_size
test_dataloader = DataLoader(test_dataset, batch_size=eval_batch_size, shuffle=False)

model.eval() # Set model to evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

correct_predictions = 0
total_samples = len(test_data) # Total samples from the original split

print("Starting batched prediction...")

with torch.no_grad(): # Disable gradient calculations for inference
    for batch_idx, batch in enumerate(test_dataloader):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        # Generate predictions
        generated_ids = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=256, # Adjust as needed
            num_beams=1, # Greedy decoding for simplicity
            do_sample=False # No sampling
        )

        # Decode the generated IDs for the current batch
        decoded_preds_batch = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

        # Process predictions for the current batch
        for i, pred_string in enumerate(decoded_preds_batch):
            original_data_index = batch_idx * eval_batch_size + i
            sql = test_data[original_data_index]["SQL"]
            true_mongo = test_data[original_data_index]["generated_nosql"].strip()

            prompt_for_sample = build_sql_to_mongo_prompt(sql)

            # The generated output contains the prompt, so remove it
            predicted_mongo = pred_string.replace(prompt_for_sample, "").strip()
            if predicted_mongo.endswith("</s>"): # Remove potential end token
                predicted_mongo = predicted_mongo[:-4].strip()

            if predicted_mongo == true_mongo:
                correct_predictions += 1

        # Optional: Clear cache after each batch if memory is still critical
        # This is already done at the start of the cell, but can be done here too for very large models/batches
        torch.cuda.empty_cache()

accuracy = correct_predictions / total_samples
print(f"Exact Match Accuracy on Test Set: {accuracy * 100:.2f}%")

# --- END MANUAL PREDICTION LOOP ---



import nltk
from nltk.translate.bleu_score import corpus_bleu
from nltk.tokenize import word_tokenize

# Install nltk if it's not already installed
try:
    import nltk
except ImportError:
    !pip install nltk
    import nltk

# Download the 'punkt' tokenizer data if not already present
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

print("NLTK, 'punkt' tokenizer, and BLEU score functions are ready.")

import torch
from torch.utils.data import DataLoader
import nltk
from nltk.translate.bleu_score import corpus_bleu
from nltk.tokenize import word_tokenize

# Ensure punkt_tab is downloaded for word_tokenize
try:
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

# Initialize lists for BLEU score calculation
all_true_mongo_tokenized = []
all_predicted_mongo_tokenized = []

# Re-initialize the Trainer just to ensure args are set, though not directly used for prediction here
# The model weights are already loaded.
from transformers import Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=None, # No need for train_dataset for prediction only
    tokenizer=tokenizer
)

# Clear CUDA cache before prediction to free up memory
torch.cuda.empty_cache()

# Use a DataLoader for batching during manual inference
eval_batch_size = training_args.per_device_eval_batch_size
test_dataloader = DataLoader(test_dataset, batch_size=eval_batch_size, shuffle=False)

model.eval() # Set model to evaluation mode
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("Starting batched prediction for BLEU score calculation...")

with torch.no_grad(): # Disable gradient calculations for inference
    for batch_idx, batch in enumerate(test_dataloader):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        # Generate predictions
        generated_ids = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=256, # Adjust as needed
            num_beams=1, # Greedy decoding for simplicity
            do_sample=False # No sampling
        )

        # Decode the generated IDs for the current batch
        decoded_preds_batch = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)

        # Process predictions for the current batch
        for i, pred_string in enumerate(decoded_preds_batch):
            original_data_index = batch_idx * eval_batch_size + i
            sql = test_data[original_data_index]["SQL"]
            true_mongo = test_data[original_data_index]["generated_nosql"].strip()

            prompt_for_sample = build_sql_to_mongo_prompt(sql)

            # The generated output contains the prompt, so remove it
            predicted_mongo = pred_string.replace(prompt_for_sample, "").strip()
            if predicted_mongo.endswith("</s>"): # Remove potential end token
                predicted_mongo = predicted_mongo[:-4].strip()

            # Tokenize and store for BLEU calculation
            all_true_mongo_tokenized.append([word_tokenize(true_mongo)]) # corpus_bleu expects a list of references
            all_predicted_mongo_tokenized.append(word_tokenize(predicted_mongo))

        torch.cuda.empty_cache()

# Calculate BLEU score
bleu_score = corpus_bleu(all_true_mongo_tokenized, all_predicted_mongo_tokenized)
print(f"BLEU Score on Test Set: {bleu_score * 100:.2f}%")
