# -*- coding: utf-8 -*-
"""TrainSql2NoSql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-uYnrUVWFooLVImCTQ5w-SRgQmSlDY6
"""

from zipfile import ZipFile
import os

ZIP_PATH = "/content/sql_lora_finetune_ready.zip"
EXTRACT_PATH = "/content/sql_lora"

os.makedirs(EXTRACT_PATH, exist_ok=True)

with ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_PATH)

print("Extracted files:", os.listdir(EXTRACT_PATH))

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

BASE_MODEL = "meta-llama/Llama-3.2-3B"
EXISTING_LORA = "/content/sql_lora/content/sql_lora_out/peft"
TOKENIZER_PATH = "/content/sql_lora/content/sql_lora_out/tokenizer"

tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_PATH)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

# 🔥 Load EXACT same LoRA adapter
model = PeftModel.from_pretrained(base_model, EXISTING_LORA)
model.print_trainable_parameters()

model.config.use_cache = False

import json

sql_mongo_data = []

with open("/content/train_valid_nosql_pass1.json", "r") as f:
    for line in f:
        line = line.strip()
        if line:  # skip empty lines
            sql_mongo_data.append(json.loads(line))

print("Loaded samples:", len(sql_mongo_data))
print("First sample keys:", sql_mongo_data[0].keys())

def build_sql_to_mongo_prompt(sql):
    return (
        "<s>Convert this SQL query to an equivalent MongoDB query.\n\n"
        "Rules:\n"
        "1. Output ONLY MongoDB query.\n"
        "2. Use aggregate() for JOIN or GROUP BY.\n"
        "3. No explanation.\n\n"
        f"SQL:\n{sql}\n\n"
        "MongoDB:\n"
    )

from torch.utils.data import Dataset

class SQLToMongoDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=1024):
        self.data = data
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sql = self.data[idx]["SQL"].strip()
        mongo = self.data[idx]["generated_nosql"].strip()

        prompt = build_sql_to_mongo_prompt(sql)
        full_text = f"{prompt}{mongo}</s>"

        enc = self.tokenizer(
            full_text,
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt"
        )

        input_ids = enc["input_ids"].squeeze(0)
        labels = input_ids.clone()

        prompt_len = len(self.tokenizer(prompt)["input_ids"])
        labels[:prompt_len] = -100  # 🔥 mask SQL

        return {
            "input_ids": input_ids,
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": labels,
        }



train_dataset = SQLToMongoDataset(sql_mongo_data, tokenizer)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/sql_lora_extended",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,   # 🔥 low LR
    warmup_steps=10,

    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    remove_unused_columns=False,
    report_to="none",
)

from peft.tuners.lora import LoraLayer

# 1. Freeze everything
for p in model.parameters():
    p.requires_grad = False

# 2. Unfreeze ONLY LoRA matrices (A and B)
for module in model.modules():
    if isinstance(module, LoraLayer):
        module.lora_A["default"].weight.requires_grad = True
        module.lora_B["default"].weight.requires_grad = True

model.print_trainable_parameters()

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    processing_class=tokenizer
)

trainer.train()

trainer.save_model("/content/sql_lora_out/peft")

trainer.save_model("/content/sql_lora_out_sql_mongo/peft")
tokenizer.save_pretrained("/content/sql_lora_out_sql_mongo/tokenizer")

import shutil
import os

LORA_DIR = "/content/sql_lora_out"
ZIP_PATH = "/content/sql_lora_sql_to_mongo"

assert os.path.exists(LORA_DIR), "LoRA directory not found!"

shutil.make_archive(
    ZIP_PATH,
    "zip",
    LORA_DIR
)

print("ZIP created at:", ZIP_PATH + ".zip")