"""
Evaluation metrics for Text-to-SQL models.

This module provides functions to compute evaluation metrics including
exact match accuracy and execution accuracy.
"""

import re
import sqlite3
from typing import Optional, Tuple


def normalize_sql(sql: str) -> str:
    """
    Normalize SQL query for comparison.
    
    Args:
        sql: SQL query string
        
    Returns:
        Normalized SQL query (lowercase, whitespace normalized)
    """
    # Convert to lowercase
    sql = sql.lower()
    
    # Remove extra whitespace
    sql = re.sub(r'\s+', ' ', sql)
    
    # Remove trailing semicolon
    sql = sql.rstrip(';')
    
    # Strip leading/trailing whitespace
    sql = sql.strip()
    
    return sql


def compute_exact_match(predicted: str, reference: str) -> bool:
    """
    Computes Exact Match accuracy by comparing normalized SQL strings.
    
    Args:
        predicted: SQL query generated by the model
        reference: Ground truth SQL query
        
    Returns:
        True if queries match (case-insensitive, whitespace-normalized), False otherwise
    """
    # Normalize both queries
    pred_normalized = normalize_sql(predicted)
    ref_normalized = normalize_sql(reference)
    
    return pred_normalized == ref_normalized


def execute_sql(sql: str, db_path: str) -> Tuple[bool, Optional[list], Optional[str]]:
    """
    Execute SQL query on SQLite database.
    
    Args:
        sql: SQL query to execute
        db_path: Path to SQLite database file
        
    Returns:
        Tuple of (success, results, error_message)
        - success: True if execution succeeded
        - results: List of rows if successful, None otherwise
        - error_message: Error message if failed, None otherwise
    """
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Execute query
        cursor.execute(sql)
        results = cursor.fetchall()
        
        conn.close()
        
        return True, results, None
        
    except Exception as e:
        return False, None, str(e)


def compare_results(results1: list, results2: list) -> bool:
    """
    Compare two query result sets.
    
    Args:
        results1: First result set
        results2: Second result set
        
    Returns:
        True if results are identical (order-insensitive for some cases)
    """
    # Convert to sets of tuples for comparison
    # This handles order differences in some cases
    try:
        set1 = set(tuple(row) for row in results1)
        set2 = set(tuple(row) for row in results2)
        return set1 == set2
    except TypeError:
        # If results contain unhashable types, fall back to direct comparison
        return sorted(results1) == sorted(results2)


def compute_execution_accuracy(
    predicted: str,
    reference: str,
    db_path: str,
    verbose: bool = False
) -> bool:
    """
    Computes Execution Accuracy by running both queries and comparing results.
    
    Args:
        predicted: SQL query generated by the model
        reference: Ground truth SQL query
        db_path: Path to the SQLite database file
        verbose: If True, print detailed error messages
        
    Returns:
        True if both queries return the same results, False otherwise
    """
    # Execute predicted query
    pred_success, pred_results, pred_error = execute_sql(predicted, db_path)
    
    if not pred_success:
        if verbose:
            print(f"  ✗ Predicted query failed: {pred_error}")
        return False
    
    # Execute reference query
    ref_success, ref_results, ref_error = execute_sql(reference, db_path)
    
    if not ref_success:
        if verbose:
            print(f"  ✗ Reference query failed: {ref_error}")
            print(f"    This may indicate an issue with the dataset.")
        return False
    
    # Compare results
    match = compare_results(pred_results, ref_results)
    
    if verbose and not match:
        print(f"  ✗ Results don't match:")
        print(f"    Predicted: {pred_results[:3]}...")
        print(f"    Reference: {ref_results[:3]}...")
    
    return match


def compute_metrics(
    exact_matches: list[bool],
    execution_matches: list[bool]
) -> dict[str, float]:
    """
    Compute aggregate metrics from individual results.
    
    Args:
        exact_matches: List of exact match results (True/False)
        execution_matches: List of execution accuracy results (True/False)
        
    Returns:
        Dictionary with accuracy percentages
    """
    total = len(exact_matches)
    
    if total == 0:
        return {
            'exact_match_accuracy': 0.0,
            'execution_accuracy': 0.0,
            'total_examples': 0
        }
    
    exact_match_count = sum(exact_matches)
    execution_count = sum(execution_matches)
    
    return {
        'exact_match_accuracy': (exact_match_count / total) * 100,
        'execution_accuracy': (execution_count / total) * 100,
        'total_examples': total,
        'exact_match_count': exact_match_count,
        'execution_count': execution_count
    }
