def compute_exact_match(predicted: str, reference: str) -> bool:
    """
    Computes Exact Match accuracy by comparing normalized SQL strings.
    
    Args:
        predicted: SQL query generated by the model
        reference: Ground truth SQL query
        
    Returns:
        True if queries match (case-insensitive, whitespace-normalized), False otherwise
    """
    # Normalize whitespace and case
    return predicted.strip().lower() == reference.strip().lower()

def compute_execution_accuracy(predicted: str, reference: str, db_path: str) -> bool:
    """
    Computes Execution Accuracy by running both queries and comparing results.
    Placeholder implementation.
    
    Args:
        predicted: SQL query generated by the model
        reference: Ground truth SQL query
        db_path: Path to the SQLite database file
        
    Returns:
        True if both queries return the same results, False otherwise
        
    Note:
        Currently returns False as execution logic is not implemented yet.
    """
    # TODO: Implement execution on actual database using sqlite3
    # For now, just return False as we don't have a DB setup
    print(f"Warning: Execution accuracy not implemented yet. Comparing: {predicted} vs {reference}")
    return False
